[phases.setup]
nixPkgs = [
  "chromium",
  "nss",
  "freetype",
  "harfbuzz",
  "ca-certificates",
  "glib",
  "dbus",
  "xorg.libX11",
  "xorg.libXcomposite",
  "xorg.libXdamage",
  "xorg.libXext",
  "xorg.libXfixes",
  "xorg.libXrandr",
  "xorg.libxcb",
  "expat",
  "xorg.libXcursor",
  "xorg.libXi",
]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "playwright install --with-deps chromium",
]
